// Donnees du portfolio -- generees a partir du contenu reel de /Portfolio.
// Regenere automatiquement (generate-data-js.ps1) a chaque reorganisation
// du dossier Portfolio.
// Phase 3 (automatisation) remplacera ce fichier par un flux dynamique
// alimente par l'API WordPress (dossier depose -> page creee).

const CATEGORIES = [
  { key: "architecture", label: "Architecture" },
  { key: "autoroute", label: "Autoroute" },
  { key: "design", label: "Design" },
  { key: "industrie", label: "Industrie" },
  { key: "irve", label: "IRVE" },
  { key: "films", label: "Films" },
];

const PROJECTS = [
  {
    slug: "a-gram-moulin",
    title: "A-Gram — Moulin",
    client: "A-Gram",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/A-Gram_Moulin/texte.txt",
    video: "Portfolio/Images/Architecture/A-Gram_Moulin/vignette.mp4",
    images: [
      "Portfolio/Images/Architecture/A-Gram_Moulin/_Pers 1.jpg",
      "Portfolio/Images/Architecture/A-Gram_Moulin/Pers 2.jpg",
      "Portfolio/Images/Architecture/A-Gram_Moulin/Pers 3.jpg",
      "Portfolio/Images/Architecture/A-Gram_Moulin/Pers 4.jpg",
    ],
  },
  {
    slug: "atelier-si-architecture-cap-ferret",
    title: "Atelier SI Architecture — Cap Ferret",
    client: "Atelier SI Architecture",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Atelier SI Architecture_Cap Ferret/texte.txt",
    video: "Portfolio/Images/Architecture/Atelier SI Architecture_Cap Ferret/vignette.mp4",
    images: [
      "Portfolio/Images/Architecture/Atelier SI Architecture_Cap Ferret/_Insert 3.jpg",
      "Portfolio/Images/Architecture/Atelier SI Architecture_Cap Ferret/Insert 2.jpg",
      "Portfolio/Images/Architecture/Atelier SI Architecture_Cap Ferret/Pers_Piscine.jpg",
    ],
  },
  {
    slug: "br-architecture-blancheteau",
    title: "BR-Architecture — Blancheteau",
    client: "BR-Architecture",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/BR-Architecture_Blancheteau/texte.txt",
    video: "Portfolio/Images/Architecture/BR-Architecture_Blancheteau/PD_Animate-Image_Kling o3_6a8fe3c082f0fd6290eab2f3-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/BR-Architecture_Blancheteau/_Pers_2.jpg",
      "Portfolio/Images/Architecture/BR-Architecture_Blancheteau/Pers_3.jpg",
    ],
  },
  {
    slug: "br-architecture-le-ciem",
    title: "BR-Architecture — Le Ciem",
    client: "BR-Architecture",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/BR-Architecture_Le Ciem/texte.txt",
    images: [
      "Portfolio/Images/Architecture/BR-Architecture_Le Ciem/_Pers0001_v2.jpg",
      "Portfolio/Images/Architecture/BR-Architecture_Le Ciem/Pers0003.jpg",
      "Portfolio/Images/Architecture/BR-Architecture_Le Ciem/Pers0004.jpg",
    ],
  },
  {
    slug: "condesse-et-schneider-abidjan",
    title: "Condesse et Schneider — Abidjan",
    client: "Condesse et Schneider",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Condesse et Schneider_Abidjan/texte.txt",
    video: "Portfolio/Images/Architecture/Condesse et Schneider_Abidjan/PD_Animate-Image_Kling o3_6a8fe5a382f0fd6290ead7d3-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/Condesse et Schneider_Abidjan/_V1_A2_Night-enhanced.jpg",
      "Portfolio/Images/Architecture/Condesse et Schneider_Abidjan/V1_A2_Day-enhanced.jpg",
      "Portfolio/Images/Architecture/Condesse et Schneider_Abidjan/V2_Jour_A2_0002.jpg",
    ],
  },
  {
    slug: "martha-emirza-andernos",
    title: "Martha Emirza — Andernos",
    client: "Martha Emirza",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Martha Emirza_Andernos/texte.txt",
    video: "Portfolio/Images/Architecture/Martha Emirza_Andernos/vignette.mp4",
    images: [
      "Portfolio/Images/Architecture/Martha Emirza_Andernos/Jour0001.jpg",
    ],
  },
  {
    slug: "moonsafari-addictologie",
    title: "MoonSafari — Addictologie",
    client: "MoonSafari",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/MoonSafari_Addictologie/texte.txt",
    video: "Portfolio/Images/Architecture/MoonSafari_Addictologie/PD_Animate-Image_Kling o3_6a90436363ada9c0dd68e9fc-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/MoonSafari_Addictologie/_Chambre0001.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Addictologie/Int_Circulation0002.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Addictologie/Pers0001.jpg",
    ],
  },
  {
    slug: "moonsafari-arcachon",
    title: "MoonSafari — Arcachon",
    client: "MoonSafari",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/MoonSafari_Arcachon/texte.txt",
    video: "Portfolio/Images/Architecture/MoonSafari_Arcachon/PD_Animate-Image_Kling o3_6a8d8e25d97c01e403b741f1-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/MoonSafari_Arcachon/_Biblio0001-enhanced (1).jpg",
      "Portfolio/Images/Architecture/MoonSafari_Arcachon/Pers0001.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Arcachon/Pers0002.jpg",
    ],
  },
  {
    slug: "moonsafari-canet-des-maures",
    title: "MoonSafari — Canet des Maures",
    client: "MoonSafari",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/MoonSafari_Canet des Maures/texte.txt",
    images: [
      "Portfolio/Images/Architecture/MoonSafari_Canet des Maures/_Pers 2.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Canet des Maures/Pers_v20001.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Canet des Maures/Pers_v20003.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Canet des Maures/Pers_v20004.jpg",
    ],
  },
  {
    slug: "moonsafari-chantecrit",
    title: "MoonSafari — Chantecrit",
    client: "MoonSafari",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/MoonSafari_Chantecrit/texte.txt",
    video: "Portfolio/Images/Architecture/MoonSafari_Chantecrit/PD_Animate-Image_Kling o3_6a9043f463ada9c0dd68ffc3-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/MoonSafari_Chantecrit/_Perspective0001.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Chantecrit/Perspective0002.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Chantecrit/Perspective0003.jpg",
    ],
  },
  {
    slug: "moonsafari-lormont",
    title: "MoonSafari — Lormont",
    client: "MoonSafari",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/MoonSafari_Lormont/texte.txt",
    video: "Portfolio/Images/Architecture/MoonSafari_Lormont/PD_Animate-Image_Kling o3_6a8feacf82f0fd6290eb4c83-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/MoonSafari_Lormont/_Classe Maternelle_0006-enhanced.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Lormont/Circulation Entree_0009-enhanced.jpg",
      "Portfolio/Images/Architecture/MoonSafari_Lormont/Entree_1_0001.jpg",
    ],
  },
  {
    slug: "moonsafari-villefranche",
    title: "MoonSafari — VilleFranche",
    client: "MoonSafari",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/MoonSafari_VilleFranche/texte.txt",
    images: [
      "Portfolio/Images/Architecture/MoonSafari_VilleFranche/_Pers_2-enhanced.jpg",
      "Portfolio/Images/Architecture/MoonSafari_VilleFranche/magnific-ykiXfGfytCHAPQ1XEMVl-Pers_3_2k.jpg",
    ],
  },
  {
    slug: "plus-architecte-saucats",
    title: "Plus Architecte — Saucats",
    client: "Plus Architecte",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Plus Architecte_Saucats/texte.txt",
    video: "Portfolio/Images/Architecture/Plus Architecte_Saucats/PD_Animate-Image_Kling o3_6a9043b663ada9c0dd68f56c-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/Plus Architecte_Saucats/Jour0001.jpg",
    ],
  },
  {
    slug: "renard-blaye",
    title: "Renard — Blaye",
    client: "Renard",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Renard_Blaye/texte.txt",
    video: "Portfolio/Images/Architecture/Renard_Blaye/PD_Animate-Image_Kling o3_6a8feb3682f0fd6290eb588d-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/Renard_Blaye/_Jour0002.jpg",
      "Portfolio/Images/Architecture/Renard_Blaye/Int0003.jpg",
      "Portfolio/Images/Architecture/Renard_Blaye/Jour0001.jpg",
    ],
  },
  {
    slug: "renard-creps",
    title: "Renard — Creps",
    client: "Renard",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Renard_Creps/texte.txt",
    images: [
      "Portfolio/Images/Architecture/Renard_Creps/Pers0002.jpg",
    ],
  },
  {
    slug: "renard-lacanau",
    title: "Renard — Lacanau",
    client: "Renard",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Renard_Lacanau/texte.txt",
    video: "Portfolio/Images/Architecture/Renard_Lacanau/PD_Animate-Image_Kling o3_6a8fec1682f0fd6290eb7252-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/Renard_Lacanau/_Pers0002.jpg",
      "Portfolio/Images/Architecture/Renard_Lacanau/Pers0001.jpg",
      "Portfolio/Images/Architecture/Renard_Lacanau/Pers0003.jpg",
    ],
  },
  {
    slug: "studio-hybride-mons",
    title: "Studio Hybride — Mons",
    client: "Studio Hybride",
    category: "architecture",
    textFile: "Portfolio/Images/Architecture/Studio Hybride_Mons/texte.txt",
    video: "Portfolio/Images/Architecture/Studio Hybride_Mons/PD_Animate-Image_Kling o3_6a8fecd982f0fd6290eb84a4-0_1.mp4",
    images: [
      "Portfolio/Images/Architecture/Studio Hybride_Mons/_Pers_Sol.jpg",
      "Portfolio/Images/Architecture/Studio Hybride_Mons/Generated Image March 04, 2026 - 3_35PM.jpg",
      "Portfolio/Images/Architecture/Studio Hybride_Mons/Generated Image March 04, 2026 - 3_37PM.jpg",
    ],
  },
  {
    slug: "certas-bolleville",
    title: "Certas — Bolleville",
    client: "Certas",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/Certas_Bolleville/texte.txt",
    images: [
      "Portfolio/Images/Autoroute/Certas_Bolleville/_Jour0001.jpg",
      "Portfolio/Images/Autoroute/Certas_Bolleville/Jour0002.jpg",
      "Portfolio/Images/Autoroute/Certas_Bolleville/Jour0003.jpg",
      "Portfolio/Images/Autoroute/Certas_Bolleville/Jour0004.jpg",
    ],
  },
  {
    slug: "moonsafari-applegreen",
    title: "MoonSafari — AppleGreen",
    client: "MoonSafari",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/MoonSafari_AppleGreen/texte.txt",
    images: [
      "Portfolio/Images/Autoroute/MoonSafari_AppleGreen/_Jour0001.jpg",
      "Portfolio/Images/Autoroute/MoonSafari_AppleGreen/Jour0003.jpg",
      "Portfolio/Images/Autoroute/MoonSafari_AppleGreen/Jour0005.jpg",
      "Portfolio/Images/Autoroute/MoonSafari_AppleGreen/Jour0006.jpg",
    ],
  },
  {
    slug: "picoty-argentan",
    title: "Picoty — Argentan",
    client: "Picoty",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/Picoty_Argentan/texte.txt",
    images: [
      "Portfolio/Images/Autoroute/Picoty_Argentan/Ext_1 copie.jpg",
      "Portfolio/Images/Autoroute/Picoty_Argentan/Int_1 copie.jpg",
      "Portfolio/Images/Autoroute/Picoty_Argentan/Int_4 copie.jpg",
    ],
  },
  {
    slug: "picoty-comminges",
    title: "Picoty — Comminges",
    client: "Picoty",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/Picoty_Comminges/texte.txt",
    images: [
      "Portfolio/Images/Autoroute/Picoty_Comminges/_Pers_Ext0001.jpg",
      "Portfolio/Images/Autoroute/Picoty_Comminges/Pers_Ext0002_1.jpg",
      "Portfolio/Images/Autoroute/Picoty_Comminges/Pers_Ext0003.jpg",
      "Portfolio/Images/Autoroute/Picoty_Comminges/Pers_Ext0006.jpg",
      "Portfolio/Images/Autoroute/Picoty_Comminges/Pers_Int0004.jpg",
      "Portfolio/Images/Autoroute/Picoty_Comminges/Pers_Int0005.jpg",
    ],
  },
  {
    slug: "picoty-les-palombieres",
    title: "Picoty — Les Palombières",
    client: "Picoty",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/Picoty_Les Palombières/texte.txt",
    images: [
      "Portfolio/Images/Autoroute/Picoty_Les Palombières/_Pers0001.jpg",
      "Portfolio/Images/Autoroute/Picoty_Les Palombières/Pers0004.jpg",
      "Portfolio/Images/Autoroute/Picoty_Les Palombières/Pers0005.jpg",
      "Portfolio/Images/Autoroute/Picoty_Les Palombières/Pers0006.jpg",
    ],
  },
  {
    slug: "picoty-loiret",
    title: "Picoty — Loiret",
    client: "Picoty",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/Picoty_Loiret/texte.txt",
    video: "Portfolio/Images/Autoroute/Picoty_Loiret/PD_Animate-Image_Kling o3_6a8fec7e82f0fd6290eb7b28-0_1.mp4",
    images: [
      "Portfolio/Images/Autoroute/Picoty_Loiret/_Jour0002.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Int0008.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Int0009.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Jour0001.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Jour0003.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Jour0004.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Jour0005.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Jour0006.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Jour0007.jpg",
      "Portfolio/Images/Autoroute/Picoty_Loiret/Nuit0000.jpg",
    ],
  },
  {
    slug: "picoty-sarthe-touraine",
    title: "Picoty — Sarthe Touraine",
    client: "Picoty",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/texte.txt",
    images: [
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/_Ext0002.jpg",
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/Ext0001.jpg",
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/Ext0003.jpg",
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/Ext0004.jpg",
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/Ext0005.jpg",
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/Ext0008.jpg",
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/Ext0009.jpg",
      "Portfolio/Images/Autoroute/Picoty_Sarthe Touraine/Sanitaires0001.jpg",
    ],
  },
  {
    slug: "shell-beuzeville",
    title: "Shell — Beuzeville",
    client: "Shell",
    category: "autoroute",
    images: [
      "Portfolio/Images/Autoroute/Shell_Beuzeville/_Sans titre-3.jpg",
      "Portfolio/Images/Autoroute/Shell_Beuzeville/Sans titre-2.jpg",
      "Portfolio/Images/Autoroute/Shell_Beuzeville/Sans titre-4.jpg",
    ],
  },
  {
    slug: "shell-sentinelle",
    title: "Shell — Sentinelle",
    client: "Shell",
    category: "autoroute",
    video: "Portfolio/Images/Autoroute/Shell_Sentinelle/PD_Animate-Image_Kling o3_6a90355463ada9c0dd66dec4-0_1.mp4",
    images: [
      "Portfolio/Images/Autoroute/Shell_Sentinelle/_Sans titre-1.jpg",
    ],
  },
  {
    slug: "total-lauragais",
    title: "Total — Lauragais",
    client: "Total",
    category: "autoroute",
    textFile: "Portfolio/Images/Autoroute/Total_Lauragais/texte.txt",
    images: [
      "Portfolio/Images/Autoroute/Total_Lauragais/_Ext0004.jpg",
      "Portfolio/Images/Autoroute/Total_Lauragais/Ext0001-enhanced.jpg",
      "Portfolio/Images/Autoroute/Total_Lauragais/Ext0003.jpg",
      "Portfolio/Images/Autoroute/Total_Lauragais/Int0012.jpg",
      "Portfolio/Images/Autoroute/Total_Lauragais/Int0013.jpg",
    ],
  },
  {
    slug: "vinci-a154",
    title: "Vinci — A154",
    client: "Vinci",
    category: "autoroute",
    images: [
      "Portfolio/Images/Autoroute/Vinci_A154/Sans titre-1.jpg",
      "Portfolio/Images/Autoroute/Vinci_A154/Sans titre-2.jpg",
      "Portfolio/Images/Autoroute/Vinci_A154/Sans titre-3.jpg",
    ],
  },
  {
    slug: "vinexia-thienot",
    title: "Vinexia — Thienot",
    client: "Vinexia",
    category: "design",
    textFile: "Portfolio/Images/Design/Vinexia_Thienot/texte.txt",
    images: [
      "Portfolio/Images/Design/Vinexia_Thienot/_Bar_a_Champagne_3.jpg",
      "Portfolio/Images/Design/Vinexia_Thienot/Chambre.jpg",
      "Portfolio/Images/Design/Vinexia_Thienot/Vinothèque.jpg",
    ],
  },
  {
    slug: "comquest-ligne-de-production",
    title: "ComQuest — Ligne de Production",
    client: "ComQuest",
    category: "industrie",
    textFile: "Portfolio/Images/Industrie/ComQuest_Ligne de Production/texte.txt",
    images: [
      "Portfolio/Images/Industrie/ComQuest_Ligne de Production/Pers0001.jpg",
      "Portfolio/Images/Industrie/ComQuest_Ligne de Production/Pers0002.jpg",
    ],
  },
  {
    slug: "jacq-mios",
    title: "Jacq — Mios",
    client: "Jacq",
    category: "industrie",
    textFile: "Portfolio/Images/Industrie/Jacq_Mios/texte.txt",
    images: [
      "Portfolio/Images/Industrie/Jacq_Mios/Insertion_1.jpg",
      "Portfolio/Images/Industrie/Jacq_Mios/Insertion_2_PV.jpg",
      "Portfolio/Images/Industrie/Jacq_Mios/Insertion_3_PV.jpg",
    ],
  },
  {
    slug: "allego-la-grand-croix",
    title: "Allego — La Grand Croix",
    client: "Allego",
    category: "irve",
    textFile: "Portfolio/Images/IRVE/Allego_La Grand Croix/texte.txt",
    images: [
      "Portfolio/Images/IRVE/Allego_La Grand Croix/Insertion_01.jpg",
    ],
  },
  {
    slug: "bp-dix-sept-setiers",
    title: "BP — Dix Sept Setiers",
    client: "BP",
    category: "irve",
    textFile: "Portfolio/Images/IRVE/BP_Dix Sept Setiers/texte.txt",
    video: "Portfolio/Images/IRVE/BP_Dix Sept Setiers/PD_Animate-Image_Kling o3_6a90423563ada9c0dd68c5af-0_1.mp4",
    images: [
      "Portfolio/Images/IRVE/BP_Dix Sept Setiers/_vue_4.jpg",
      "Portfolio/Images/IRVE/BP_Dix Sept Setiers/vue_1.jpg",
      "Portfolio/Images/IRVE/BP_Dix Sept Setiers/vue_2.jpg",
      "Portfolio/Images/IRVE/BP_Dix Sept Setiers/vue_3.jpg",
    ],
  },
  {
    slug: "total-linkcity",
    title: "Total — Linkcity",
    client: "Total",
    category: "irve",
    textFile: "Portfolio/Images/IRVE/Total_Linkcity/texte.txt",
    images: [
      "Portfolio/Images/IRVE/Total_Linkcity/_Jour0002.jpg",
      "Portfolio/Images/IRVE/Total_Linkcity/Jour0001.jpg",
      "Portfolio/Images/IRVE/Total_Linkcity/Jour0003.jpg",
    ],
  },
  {
    slug: "volta-grand-var",
    title: "Volta — Grand Var",
    client: "Volta",
    category: "irve",
    textFile: "Portfolio/Images/IRVE/Volta_Grand Var/texte.txt",
    images: [
      "Portfolio/Images/IRVE/Volta_Grand Var/_Volta0009.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0001.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0002.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0003.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0004.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0005.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0006.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0007.jpg",
      "Portfolio/Images/IRVE/Volta_Grand Var/Volta0008.jpg",
    ],
  },
  {
    slug: "voltix-site",
    title: "Voltix — Site",
    client: "Voltix",
    category: "irve",
    video: "Portfolio/Images/IRVE/Voltix_Site/PD_Animate-Image_Kling o3_6a903be863ada9c0dd67d968-0_1.mp4",
    images: [
      "Portfolio/Images/IRVE/Voltix_Site/_Sans titre-2.jpg",
      "Portfolio/Images/IRVE/Voltix_Site/Sans titre-1.jpg",
    ],
  },
  {
    slug: "zunder-site",
    title: "Zunder — Site",
    client: "Zunder",
    category: "irve",
    textFile: "Portfolio/Images/IRVE/Zunder_Site/texte.txt",
    images: [
      "Portfolio/Images/IRVE/Zunder_Site/Jour0001.jpg",
      "Portfolio/Images/IRVE/Zunder_Site/Jour0004.jpg",
    ],
  },
  {
    slug: "grain-blanc-terega",
    title: "Grain Blanc — Terega",
    client: "Grain Blanc",
    category: "films",
    textFile: "Portfolio/Films/Grain Blanc_Terega/texte.txt",
    video: "Portfolio/Films/Grain Blanc_Terega/TSO_film_H2_10052022_1.mp4",
    images: [
      "Portfolio/Films/Grain Blanc_Terega/Screen.jpg",
    ],
  },
];
